Rebuild/reorganize CI scripts

diff --git a/.ci/test/behat/cleanup b/.ci/test/behat/cleanup
--- a/.ci/test/behat/cleanup
+++ b/.ci/test/behat/cleanup
@@ -1,15 +1,16 @@
 #!/bin/bash
 
-if [[ ${CI_BRANCH} != "master" && -z ${PR_NUMBER} ]];
-then
-  echo -e "CI will only deploy to Pantheon if on the master branch or creating a pull requests.\n"
-  exit 0;
-fi
+set -eo pipefail
 
-echo "::::::::::::::::::::::::::::::::::::::::::::::::"
-echo "Behat clean up on site: $TERMINUS_SITE.$TERMINUS_ENV"
-echo "::::::::::::::::::::::::::::::::::::::::::::::::"
-echo
+#
+# This script runs cleanup after Behat tests complete.
+#
+
+# Set environment varaibles
+/build-tools-ci/scripts/set-environment
+
+# Authenticate with Terminus
+terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
 
 # Restore the DB backup made before testing
 terminus -n backup:restore $TERMINUS_SITE.$TERMINUS_ENV --element=database --yes
diff --git a/.ci/test/behat/run b/.ci/test/behat/run
--- a/.ci/test/behat/run
+++ b/.ci/test/behat/run
@@ -1,28 +1,19 @@
 #!/bin/bash
 
-# Check if an admin user with our desired username exists
-BEHAT_ADMIN_USER_EXISTS=$(terminus -n wp ${TERMINUS_SITE}.${TERMINUS_ENV} -- user list --login=${BEHAT_ADMIN_USERNAME} --format=count)
+#
+# This script runs the Behat tests.
+#
 
-# If so, delete the existing admin user
-if [[ "$BEHAT_ADMIN_USER_EXISTS" == "1" ]]
-then
-  terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- user delete $BEHAT_ADMIN_USERNAME --yes
-fi
+# Set environment varaibles
+/build-tools-ci/scripts/set-environment
 
-# Update WordPress database
-terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- core update-db
+# Verbose mode and exit on errors
+set -ex
 
-# Create a backup before running Behat tests
-terminus -n backup:create $TERMINUS_SITE.$TERMINUS_ENV
-
-# Create the desired admin user
-terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- user create $BEHAT_ADMIN_USERNAME $BEHAT_ADMIN_EMAIL --user_pass=$BEHAT_ADMIN_PASSWORD --role=administrator
-
-# Confirm the admin user exists
-terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- user list --login=$BEHAT_ADMIN_USERNAME
-
-# Clear site cache
-terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV
+echo "::::::::::::::::::::::::::::::::::::::::::::::::"
+echo "Behat test site: $TERMINUS_SITE.$TERMINUS_ENV"
+echo "::::::::::::::::::::::::::::::::::::::::::::::::"
+echo
 
 # Dynamically set Behat configuration parameters
 export BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"https://'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io"},"PaulGibbs\\WordpressBehatExtension":{"site_url":"https://'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io/wp","users":{"admin":{"username":"'$BEHAT_ADMIN_USERNAME'","password":"'$BEHAT_ADMIN_PASSWORD'"}},"wpcli":{"binary":"terminus -n wp '$TERMINUS_SITE'.'$TERMINUS_ENV' --"}}}}'
